/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SudokuFrame.java
 *
 * Created on Apr 7, 2009, 11:59:50 PM
 */

package com.spv.sudokuui;

import com.spv.sudoku.*;
import java.awt.BorderLayout;
import javax.swing.JToggleButton;

/**
 *
 * @author Administrator
 */
public class SudokuFrame extends javax.swing.JFrame {

    /** Creates new form SudokuFrame */
    public SudokuFrame() {
        initComponents();

        loadSudoku(new Sudoku(9, 3));
    }

    public void loadSudoku(Sudoku sudoku) {
        sudokuPanel = new SudokuPanel(sudoku);
        pnSudoku.setMaximumSize(sudokuPanel.getDimension());
        pnSudoku.setMinimumSize(sudokuPanel.getDimension());
        pnSudoku.setPreferredSize(sudokuPanel.getDimension());
        pnSudoku.removeAll();
        pnSudoku.add(sudokuPanel, BorderLayout.CENTER);
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnOptions = new javax.swing.JPanel();
        tbtAutomark = new javax.swing.JToggleButton();
        pnSudoku = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setName("SudokuFrame"); // NOI18N

        pnOptions.setMaximumSize(null);
        pnOptions.setMinimumSize(null);
        pnOptions.setPreferredSize(new java.awt.Dimension(250, 250));

        tbtAutomark.setText("Automark");
        tbtAutomark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtAutomarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOptionsLayout = new javax.swing.GroupLayout(pnOptions);
        pnOptions.setLayout(pnOptionsLayout);
        pnOptionsLayout.setHorizontalGroup(
            pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOptionsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tbtAutomark)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        pnOptionsLayout.setVerticalGroup(
            pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOptionsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tbtAutomark)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        getContentPane().add(pnOptions, java.awt.BorderLayout.WEST);

        pnSudoku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnSudoku.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnSudoku, java.awt.BorderLayout.CENTER);

        pnTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnTitle.setPreferredSize(new java.awt.Dimension(30, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTitle.setText("Sudoku");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(426, 426, 426))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        getContentPane().add(pnTitle, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtAutomarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtAutomarkActionPerformed
        // TODO add your handling code here:
        sudokuPanel.setAutomark(tbtAutomark.isSelected());
    }//GEN-LAST:event_tbtAutomarkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SudokuFrame frame = new SudokuFrame();
                frame.setVisible(true);
                //frame.loadSudoku(new Sudoku(16, 4));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnOptions;
    private javax.swing.JPanel pnSudoku;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JToggleButton tbtAutomark;
    // End of variables declaration//GEN-END:variables

    private SudokuPanel sudokuPanel;
}
